/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src\sanity\extract.json
export type Dormire = {
  _id: string;
  _type: "dormire";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  denominazione?: string;
  indirizzo?: string;
  contatti?: string;
  web?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type DormireReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "dormire";
};

export type Ospitalita = {
  _id: string;
  _type: "ospitalita";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  luogo?: string;
  slug?: Slug;
  immagine?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descrizione?: BlockContent;
  bedAndBreakfast?: Array<
    {
      _key: string;
    } & DormireReference
  >;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Galleria = {
  _id: string;
  _type: "galleria";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titolo?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Festival = {
  _id: string;
  _type: "festival";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  biglietto?: string;
  prezzo?: string;
  quantita?: number;
};

export type Giornaliero = {
  _id: string;
  _type: "giornaliero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  biglietto?: string;
  prezzo?: string;
  quantita?: number;
};

export type EventiReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventi";
};

export type Biglietto = {
  _id: string;
  _type: "biglietto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  biglietto?: EventiReference;
  prezzo?: string;
  quantita?: number;
};

export type Staff = {
  _type: "staff";
  nome?: string;
  descrizione?: string;
  immagini?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  slug?: Slug;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  homePage?: PageReference;
};

export type SplitImage = {
  _type: "splitImage";
  orientation?: "imageLeft" | "imageRight";
  title?: string;
  testo?: BlockContent;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  title?: string;
  text?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Features = {
  _type: "features";
  title?: string;
  features?: Array<{
    title?: string;
    text?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type Faqs = {
  _type: "faqs";
  title?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & Staff)
  | ({
      _key: string;
    } & SplitImage)
  | ({
      _key: string;
    } & Features)
  | ({
      _key: string;
    } & Faqs)
>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intestazione?: string;
  contenuto?: string;
  descrizione?: BlockContent;
  slug?: Slug;
  content?: PageBuilder;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ordine?: number;
};

export type Navbar = {
  _type: "Navbar";
  navbarLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navbarLinks?: Array<{
    voce?: string;
    _type: "Menu";
    _key: string;
  }>;
};

export type Speaker = {
  _id: string;
  _type: "speaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  speakerName?: string;
  speakerImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Eventi = {
  _id: string;
  _type: "eventi";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventName?: string;
  eventType?:
    | "Inaugurazione"
    | "Trekking"
    | "Trail"
    | "Yoga"
    | "Dog Trekking"
    | "Musica"
    | "Smof Grill"
    | "Sicurezza in Natura";
  raduno?: string;
  equipaggiamento?: string;
  specifiche?: BlockContent;
  eventDescription?: BlockContent;
  relatedEvents?: Array<
    {
      _key: string;
    } & EventiReference
  >;
  slug?: Slug;
  data?: string;
  dataFine?: string;
  immagine?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  immagineEvento?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  biglietto?: number;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  tipo?: string;
  link?: string;
  immagine?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  profileImage?: string;
  uid?: string;
  subscribeNewsletter?: boolean;
  role?: "user" | "admin";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Dormire
  | SanityImageAssetReference
  | DormireReference
  | Ospitalita
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Galleria
  | Festival
  | Giornaliero
  | EventiReference
  | Biglietto
  | Staff
  | PageReference
  | SiteSettings
  | SplitImage
  | Hero
  | Features
  | FaqReference
  | Faqs
  | Faq
  | PageBuilder
  | Page
  | Navbar
  | Speaker
  | Eventi
  | Partner
  | User
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src\sanity\lib\queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == 'eventi' && defined(slug.current)][0...120]    {  _id , data, dataFine , slug , eventName, eventType, eventDescription, immagine, raduno, biglietto , equipaggiamento, immagineEvento, speakers->{    speakerName,    speakerImage  }}
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  data: string | null;
  dataFine: string | null;
  slug: Slug | null;
  eventName: string | null;
  eventType:
    | "Dog Trekking"
    | "Inaugurazione"
    | "Musica"
    | "Sicurezza in Natura"
    | "Smof Grill"
    | "Trail"
    | "Trekking"
    | "Yoga"
    | null;
  eventDescription: BlockContent | null;
  immagine: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  raduno: string | null;
  biglietto: number | null;
  equipaggiamento: string | null;
  immagineEvento: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  speakers: null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: TICKET_QUERY
// Query: *[_type == "biglietto"]{  _id , prezzo, quantita , biglietto ,}
export type TICKET_QUERY_RESULT = Array<{
  _id: string;
  prezzo: string | null;
  quantita: number | null;
  biglietto: EventiReference | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: DAILY_TICKET_QUERY
// Query: *[type == "giornaliero"]{  prezzo , quantita, bigliettoGiorno}
export type DAILY_TICKET_QUERY_RESULT = Array<never>;

// Source: src\sanity\lib\queries.ts
// Variable: FESTIVAL_TICKET_QUERY
// Query: *[type == "festival"]{  prezzo, quantita, biglietto }
export type FESTIVAL_TICKET_QUERY_RESULT = Array<never>;

// Source: src\sanity\lib\queries.ts
// Variable: PARTNER_QUERY
// Query: *[_type == "partner" ]{  _id ,nome , tipo, link ,immagine}
export type PARTNER_QUERY_RESULT = Array<{
  _id: string;
  nome: string | null;
  tipo: string | null;
  link: string | null;
  immagine: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: GALLERIES_QUERY
// Query: *[_type == "galleria" && defined(slug.current)][0...20]{_id , images , titolo , slug}
export type GALLERIES_QUERY_RESULT = Array<{
  _id: string;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  titolo: string | null;
  slug: Slug | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: SINGLE_GALLERY_QUERY
// Query: *[_type == "galleria" && slug.current == $slug][0]{  _id , images , titolo }
export type SINGLE_GALLERY_QUERY_RESULT = {
  _id: string;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  titolo: string | null;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: SINGLE_OSPITALITA_QUERY
// Query: *[_type == "ospitalita" && slug.current == $slug][0]{  _id , immagine , luogo , descrizione , bedAndBreakfast[]->{    denominazione,    indirizzo,    contatti,    web  }}
export type SINGLE_OSPITALITA_QUERY_RESULT = {
  _id: string;
  immagine: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  luogo: string | null;
  descrizione: BlockContent | null;
  bedAndBreakfast: Array<{
    denominazione: string | null;
    indirizzo: string | null;
    contatti: string | null;
    web: string | null;
  }> | null;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: SINGLE_DORMIRE_QUERY
// Query: *[_type == "dormire" && slug.current == $slug][0]{  denominazione, indirizzo, contatti, web}
export type SINGLE_DORMIRE_QUERY_RESULT = {
  denominazione: string | null;
  indirizzo: string | null;
  contatti: string | null;
  web: string | null;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: DORMIRE_QUERY
// Query: *[_type == "dormire"]{  denominazione, indirizzo, contatti, web}
export type DORMIRE_QUERY_RESULT = Array<{
  denominazione: string | null;
  indirizzo: string | null;
  contatti: string | null;
  web: string | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: OSPITALITA_QUERY
// Query: *[_type == "ospitalita" && defined(slug.current)]{  _id , immagine , luogo , descrizione , bedAndBreakfast[]->{    denominazione,    indirizzo,    contatti,    web  }, slug , }
export type OSPITALITA_QUERY_RESULT = Array<{
  _id: string;
  immagine: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  luogo: string | null;
  descrizione: BlockContent | null;
  bedAndBreakfast: Array<{
    denominazione: string | null;
    indirizzo: string | null;
    contatti: string | null;
    web: string | null;
  }> | null;
  slug: Slug | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: EVENT_QUERY
// Query: *[_type == 'eventi' && slug.current == $slug][0]{  _id , eventName, specifiche , eventType, biglietto, immagine, immagineEvento, data, dataFine, eventDescription, raduno, equipaggiamento , speakers->{    speakerName,    speakerImage  }, relatedEvents[]{    _key, // necessario per il drag and drop    ...@->{_id, eventName, slug} // ricevi i campo dall' evento referente  }}
export type EVENT_QUERY_RESULT = {
  _id: string;
  eventName: string | null;
  specifiche: BlockContent | null;
  eventType:
    | "Dog Trekking"
    | "Inaugurazione"
    | "Musica"
    | "Sicurezza in Natura"
    | "Smof Grill"
    | "Trail"
    | "Trekking"
    | "Yoga"
    | null;
  biglietto: number | null;
  immagine: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  immagineEvento: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  data: string | null;
  dataFine: string | null;
  eventDescription: BlockContent | null;
  raduno: string | null;
  equipaggiamento: string | null;
  speakers: null;
  relatedEvents: Array<{
    _key: string;
    _id: string;
    eventName: string | null;
    slug: Slug | null;
  }> | null;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: EVENTS_SLUGS_QUERY
// Query: *[_type == "eventi" && defined(slug.current)]{   "slug": slug.current}
export type EVENTS_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: AUTH_USERS
// Query: *[_type == "user"] {  _id,  name,  email,  profileImage,  uid,  subscribeNewsletter,}
export type AUTH_USERS_RESULT = Array<{
  _id: string;
  name: string | null;
  email: string | null;
  profileImage: string | null;
  uid: string | null;
  subscribeNewsletter: boolean | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: SINGLE_AUTH_USER
// Query: *[_type == "user" && uid == $uid][0]{    email  }
export type SINGLE_AUTH_USER_RESULT = {
  email: string | null;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{ descrizione[]{  ..., },  mainImage ,...,  content[]{    ...,    _type == "faqs" => {      ...,      faqs[]->    }  }}
export type PAGE_QUERY_RESULT = {
  descrizione?: BlockContent;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intestazione?: string;
  contenuto?: string;
  slug?: Slug;
  content: Array<
    | {
        _key: string;
        _type: "faqs";
        title?: string;
        faqs: Array<{
          _id: string;
          _type: "faq";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          title?: string;
          body?: BlockContent;
        }> | null;
      }
    | {
        _key: string;
        _type: "features";
        title?: string;
        features?: Array<{
          title?: string;
          text?: string;
          _type: "feature";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "hero";
        title?: string;
        text?: string;
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "splitImage";
        orientation?: "imageLeft" | "imageRight";
        title?: string;
        testo?: BlockContent;
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "staff";
        nome?: string;
        descrizione?: string;
        immagini?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
        slug?: Slug;
      }
  > | null;
  ordine?: number;
} | null;

// Source: src\sanity\lib\queries.ts
// Variable: LIST_PAGE_QUERY
// Query: *[_type == "page"]  {    title,    ordine,    _id,    "slug": slug.current,    "Home": slug.current == "/"  }  | order(Home desc, ordine asc)
export type LIST_PAGE_QUERY_RESULT = Array<{
  title: string | null;
  ordine: number | null;
  _id: string;
  slug: string | null;
  Home: boolean | false;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "siteSettings"][0]{    homePage->{      ...,      content[]{        ...,        _type == "faqs" => {          ...,          faqs[]->        }      }          }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      homePage: null;
    }
  | {
      homePage: {
        _id: string;
        _type: "page";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        intestazione?: string;
        contenuto?: string;
        descrizione?: BlockContent;
        slug?: Slug;
        content: Array<
          | {
              _key: string;
              _type: "faqs";
              title?: string;
              faqs: Array<{
                _id: string;
                _type: "faq";
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                title?: string;
                body?: BlockContent;
              }> | null;
            }
          | {
              _key: string;
              _type: "features";
              title?: string;
              features?: Array<{
                title?: string;
                text?: string;
                _type: "feature";
                _key: string;
              }>;
            }
          | {
              _key: string;
              _type: "hero";
              title?: string;
              text?: string;
              images?: Array<{
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
                _key: string;
              }>;
            }
          | {
              _key: string;
              _type: "splitImage";
              orientation?: "imageLeft" | "imageRight";
              title?: string;
              testo?: BlockContent;
              images?: Array<{
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
                _key: string;
              }>;
            }
          | {
              _key: string;
              _type: "staff";
              nome?: string;
              descrizione?: string;
              immagini?: Array<{
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
                _key: string;
              }>;
              slug?: Slug;
            }
        > | null;
        mainImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        ordine?: number;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'eventi' && defined(slug.current)][0...120]\n    {\n  _id , data, dataFine , slug , eventName, eventType, eventDescription, immagine, raduno, biglietto , equipaggiamento, immagineEvento, speakers->{\n    speakerName,\n    speakerImage\n  }}": EVENTS_QUERY_RESULT;
    '*[_type == "biglietto"]{\n  _id , prezzo, quantita , biglietto ,\n}': TICKET_QUERY_RESULT;
    '*[type == "giornaliero"]{\n  prezzo , quantita, bigliettoGiorno\n}': DAILY_TICKET_QUERY_RESULT;
    '*[type == "festival"]{\n  prezzo, quantita, biglietto \n}': FESTIVAL_TICKET_QUERY_RESULT;
    '*[_type == "partner" ]{\n  _id ,nome , tipo, link ,immagine\n}': PARTNER_QUERY_RESULT;
    '*[_type == "galleria" && defined(slug.current)][0...20]{\n_id , images , titolo , slug\n}': GALLERIES_QUERY_RESULT;
    '*[_type == "galleria" && slug.current == $slug][0]{\n  _id , images , titolo \n}': SINGLE_GALLERY_QUERY_RESULT;
    '*[_type == "ospitalita" && slug.current == $slug][0]{\n  _id , immagine , luogo , descrizione , bedAndBreakfast[]->{\n    denominazione,\n    indirizzo,\n    contatti,\n    web\n  }\n}': SINGLE_OSPITALITA_QUERY_RESULT;
    '*[_type == "dormire" && slug.current == $slug][0]{\n  denominazione, indirizzo, contatti, web\n}': SINGLE_DORMIRE_QUERY_RESULT;
    '*[_type == "dormire"]{\n  denominazione, indirizzo, contatti, web\n}': DORMIRE_QUERY_RESULT;
    '*[_type == "ospitalita" && defined(slug.current)]{\n  _id , immagine , luogo , descrizione , bedAndBreakfast[]->{\n    denominazione,\n    indirizzo,\n    contatti,\n    web\n  }, slug , \n}': OSPITALITA_QUERY_RESULT;
    "*[_type == 'eventi' && slug.current == $slug][0]{\n  _id , eventName, specifiche , eventType, biglietto, immagine, immagineEvento, data, dataFine, eventDescription, raduno, equipaggiamento , speakers->{\n    speakerName,\n    speakerImage\n  }, relatedEvents[]{\n    _key, // necessario per il drag and drop\n    ...@->{_id, eventName, slug} // ricevi i campo dall' evento referente\n  }}": EVENT_QUERY_RESULT;
    '*[_type == "eventi" && defined(slug.current)]{ \n  "slug": slug.current\n}': EVENTS_SLUGS_QUERY_RESULT;
    '*[_type == "user"] {\n  _id,\n  name,\n  email,\n  profileImage,\n  uid,\n  subscribeNewsletter,\n}': AUTH_USERS_RESULT;
    '*[_type == "user" && uid == $uid][0]{\n    email\n  }': SINGLE_AUTH_USER_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n descrizione[]{\n  ...,\n }, \n mainImage ,...,\n  content[]{\n    ...,\n    _type == "faqs" => {\n      ...,\n      faqs[]->\n    }\n  }\n}': PAGE_QUERY_RESULT;
    '\n  *[_type == "page"]\n  {\n    title,\n    ordine,\n    _id,\n    "slug": slug.current,\n    "Home": slug.current == "/"\n  }\n  | order(Home desc, ordine asc)\n': LIST_PAGE_QUERY_RESULT;
    '*[_id == "siteSettings"][0]{\n    homePage->{\n      ...,\n      content[]{\n        ...,\n        _type == "faqs" => {\n          ...,\n          faqs[]->\n        }\n      }      \n    }\n  }': HOME_PAGE_QUERY_RESULT;
  }
}
